#!/bin/bash

case "${DOCKER_TAG}" in
    "v8.5.1-php56" ) VER_LIST="v8.5-php56 v8-php56 php56" ;;
	"v8.4.2-php56" ) VER_LIST="v8.4-php56" ;;
    "v8.3.2-php56" ) VER_LIST="v8.3-php56" ;;
    "v8.2.1-php56" ) VER_LIST="v8.2-php56" ;;
    "v8.1.0-php56" ) VER_LIST="v8.1-php56" ;;
    "v8.0.3-php56" ) VER_LIST="v8.0-php56" ;;
     * ) VER_LIST="" ;;
esac

for TAG in ${VER_LIST}; do
	docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${TAG}
	docker push ${DOCKER_REPO}:${TAG}
done
