#!/bin/bash

case "${CACHE_TAG}" in
    "v8.5.1-php72" ) VER_LIST="v8.5.1 v8.5-php72 v8.5 v8-php72 v8 php72 latest" ;;
    "v8.5.0-php72" ) VER_LIST="v8.5.0" ;;
	"v8.4.2-php72" ) VER_LIST="v8.4.2 v8.4-php72 v8.4" ;;
    "v8.4.1-php72" ) VER_LIST="v8.4.1" ;;
    "v8.4.0-php72" ) VER_LIST="v8.4.0" ;;
    "v8.3.2-php72" ) VER_LIST="v8.3.2 v8.3-php72 v8.3" ;;
    "v8.3.1-php72" ) VER_LIST="v8.3.1" ;;
    "v8.3.0-php72" ) VER_LIST="v8.3.0" ;;
    "v8.2.1-php72" ) VER_LIST="v8.2.1 v8.2-php72 v8.2" ;;
    "v8.2.0-php72" ) VER_LIST="v8.2.0" ;;
    "v8.1.0-php72" ) VER_LIST="v8.1.0 v8.1-php72 v8.1" ;;
    "v8.0.3-php72" ) VER_LIST="v8.0.3 v8.0-php72 v8.0" ;;
    "v8.0.2-php72" ) VER_LIST="v8.0.2" ;;
    "v8.0.1-php72" ) VER_LIST="v8.0.1" ;;
    "v8.0.0-php72" ) VER_LIST="v8.0.0" ;;
     * ) VER_LIST="" ;;
esac

for TAG in ${VER_LIST}; do
	docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${TAG}
	docker push ${DOCKER_REPO}:${TAG}
done
